[package]
name = "cortex-m-std-dummy"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.libc]
version = "0.2"

[dependencies.cortex-m]
version = "0.7"
default-features = false

[features]
all = [
    "alloc",
    "atomic",
    "fd",
    "fs",
    "io",
    "pal",
    "process",
    "sync",
    "thread",
    "thread_local",
    "unwind",
]
alloc = []
atomic = []
fd = []
fs = []
io = []
pal = []
process = []
sync = []
thread = []
thread_local = []
unwind = []

linkage_weak = []
nightly_linkage = []